// generated by ginger from go generate -- DO NOT EDIT
package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
	"log"
	"net/http"
	"strconv"
	"time"
)


type KubeResource struct {
	db gorm.DB
}

// @Title CreateKube
// @Description get string by ID
// @Accept  json
// @Param   some_id     path    int     true        "Some ID"
// @Success 201 {object} string
// @Failure 400 {object} APIError "problem decoding body"
// @Router /kube/ [post]
func (tr *KubeResource) CreateKube(c *gin.Context) {
	var kube Kube

	if c.Bind(&kube) != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding body"})
		return
	}
	//kube.Status = KubeStatus
	kube.Ginger_Created = int32(time.Now().Unix())
	tr.db.Save(&kube)

	c.JSON(http.StatusCreated, kube)
}

func (tr *KubeResource) GetAllKubes(c *gin.Context) {
	var kubes []Kube

	tr.db.Order("ginger__created desc").Find(&kubes)

	c.JSON(http.StatusOK, kubes)
}

func (tr *KubeResource) getTag(c *gin.Context) (string, error) {
	tagStr := c.Params.ByName("id")
	fmt.Println(tagStr)
	return tagStr, nil
}

func (tr *KubeResource) GetKubeByTag(c *gin.Context) {
	tag, err := tr.getTag(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem in decoding tag"})
		return
	}
	var kube Kube
	if tr.db.Where("tag = ?", tag).First(&kube).RecordNotFound() {
		c.JSON(http.StatusNotFound, gin.H{"message": "no found"})
	} else {
		c.JSON(http.StatusOK, kube)
	}
}

func (tr *KubeResource) LikeKube(c *gin.Context) {
	var kube Kube
	tag, err := tr.getTag(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem in decoding tag"})
		return
	}
	if tr.db.Where("tag = ?", tag).First(&kube).RecordNotFound() {
		c.JSON(http.StatusNotFound, gin.H{"message": "no found"})
	} else {
	        kube.Like = 10
		tr.db.Save(&kube)
		c.JSON(http.StatusOK, kube)
	}

}

func (tr *KubeResource) SearchKube(c *gin.Context) {
	var kubes []Kube
	keyword, _ := tr.getTag(c)
	if tr.db.Where("tag LIKE ? or description LIKE ?", "%"+keyword+"%", "%"+keyword+"%").Find(&kubes).Error == gorm.RecordNotFound {
		c.JSON(400, gin.H{"message": "database find error"})
		return
	}
	c.JSON(200, kubes)
}

func (tr *KubeResource) GetKube(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
            if id == 0 {
                tr.GetKubeByTag(c)
                return
            } else {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
            }
	}

	var kube Kube

	if tr.db.First(&kube, id).RecordNotFound() {
		c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
	} else {
		c.JSON(http.StatusOK, kube)
	}
}

func (tr *KubeResource) UpdateKube(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
	}

	var kube Kube

	if c.Bind(&kube) != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding body"})
		return
	}
	kube.Ginger_Id = int32(id)

	var existing Kube

	if tr.db.First(&existing, id).RecordNotFound() {
		c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
	} else {
		tr.db.Save(&kube)
		c.JSON(http.StatusOK, kube)
	}

}

func (tr *KubeResource) PatchKube(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
	}

	// this is a hack because Gin falsely claims my unmarshalled obj is invalid.
	// recovering from the panic and using my object that already has the json body bound to it.
	var json []Patch

	r := c.Bind(&json)
	if r != nil {
		fmt.Println(r)
	} else {
		if json[0].Op != "replace" && json[0].Path != "/status" {
			c.JSON(http.StatusBadRequest, gin.H{"message": "PATCH support is limited and can only replace the /status path"})
			return
		}
		var kube Kube

		if tr.db.First(&kube, id).RecordNotFound() {
			c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
		} else {
			//kube.Status = json[0].Value

			tr.db.Save(&kube)
			c.JSON(http.StatusOK, kube)
		}
	}
}

func (tr *KubeResource) DeleteKube(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
	}

	var kube Kube

	if tr.db.First(&kube, id).RecordNotFound() {
		c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
	} else {
		tr.db.Delete(&kube)
		c.Data(http.StatusNoContent, "application/json", make([]byte, 0))
	}
}

func (tr *KubeResource) getId(c *gin.Context) (int32, error) {
	idStr := c.Params.ByName("id")
	id, err := strconv.Atoi(idStr)
	if err != nil {
		log.Print(err)
		return 0, err
	}
	return int32(id), nil
}

/**
* on patching: http://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/
 *
  * patch specification https://tools.ietf.org/html/rfc5789
   * json definition http://tools.ietf.org/html/rfc6902
*/

type Patch struct {
	Op    string `json:"op" binding:"required"`
	From  string `json:"from"`
	Path  string `json:"path"`
	Value string `json:"value"`
}

