// generated by ginger from go generate -- DO NOT EDIT

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
        "github.com/tommy351/gin-cors"
)

type Config struct {
	SvcHost    string
	DbUser     string
	DbPassword string
	DbHost     string
	DbName     string
	Token      string
	Url        string
}


type KubeService struct {
}

func (s *KubeService) getDb(cfg Config) (gorm.DB, error) {
	db, err := gorm.Open("sqlite3", "./"+cfg.DbName)
	//db.LogMode(true)
	return db, err
}

func (s *KubeService) Migrate(cfg Config) error {
	db, err := s.getDb(cfg)
	if err != nil {
		return err
	}
	db.SingularTable(true)

	db.AutoMigrate(&Kube{})
	return nil
}
func (s *KubeService) Run(cfg Config) error {
	db, err := s.getDb(cfg)
	if err != nil {
		return err
	}
	db.SingularTable(true)

	kubeResource := &KubeResource{db: db}

	r := gin.Default()
	//gin.SetMode(gin.ReleaseMode)
        r.Use(cors.Middleware(cors.Options{}))

	r.GET("/kube", kubeResource.GetAllKubes)
	r.GET("/kube/:id", kubeResource.GetKube)
	r.GET("/kube/:tag", kubeResource.GetKubeByTag)
	r.POST("/kube", kubeResource.CreateKube)
	r.PUT("/kube/:id", kubeResource.UpdateKube)
	r.PATCH("/kube/:id", kubeResource.PatchKube)
	r.DELETE("/kube/:id", kubeResource.DeleteKube)

	r.Run(cfg.SvcHost)

	return nil
}

